# Introduction to pytorch

In [1]:
import torch

In [2]:
if torch.cuda.is_available:
    print(f"GPU: {torch.cuda.get_device_name()} is available")
    print(f"{torch.cuda.get_device_capability()}")

GPU: NVIDIA GeForce RTX 4070 is availableb
(8, 9)


### Basic information about the tensors
Tensor can be either:
- scalar 
- vector
- matrix
- tensor

In [3]:
scalar = torch.tensor(7)
vector = torch.tensor([1,7])
matrix = torch.tensor([[1,-1], [1,-1]])
tensor = torch.tensor([[[1,-1],[1,-1], [1,-1], [1,-1]]])

In [24]:
for k,f in {"scalar": scalar,"vector": vector,"matrix":matrix,"tensor": tensor}.items():
    print(f"{k}:", f)
    print(f"{f.size()=}")
    print(f"{f.shape=}")
    print(f"{f.dim()=}")


scalar: tensor(7)
f.size()=torch.Size([])
f.shape=torch.Size([])
f.dim()=0
vector: tensor([1, 7])
f.size()=torch.Size([2])
f.shape=torch.Size([2])
f.dim()=1
matrix: tensor([[ 1, -1],
        [ 1, -1]])
f.size()=torch.Size([2, 2])
f.shape=torch.Size([2, 2])
f.dim()=2
tensor: tensor([[[ 1, -1],
         [ 1, -1],
         [ 1, -1],
         [ 1, -1]]])
f.size()=torch.Size([1, 4, 2])
f.shape=torch.Size([1, 4, 2])
f.dim()=3


### Get information from the tensors

1. get dtype - use `tensor.dtype`
2. get shape of a tensor - use `tensor.shape`
3. get device - use `tensor.device`

In [23]:
some_tensor = torch.rand(size=(3, 4), dtype=torch.float32, device="cuda")
print(some_tensor)
print(some_tensor.dtype) # torch.float32 by default
print(some_tensor.shape) # torch.Size[3,4]
print(some_tensor.device) # cuda(0) by default cpu

print(some_tensor.size())  # semantically equivalent to `some_tensor.shape`


tensor([[0.6492, 0.3663, 0.4746, 0.9975],
        [0.1039, 0.4657, 0.4711, 0.9781],
        [0.3706, 0.2986, 0.8407, 0.7558]], device='cuda:0')
torch.float32
torch.Size([3, 4])
cuda:0
torch.Size([3, 4])


The above values accomodate almost all issues with testors:
* tensors not in the right type
* tesnors not in the right shape
* tensors not in the same device

### Manipulating tensors

Tensor operations include
* Addition
* Subtraction
* Multiplication
* Division
* Matrix multiplication (MatMul)

In [35]:
tensor = torch.tensor([1,2,3])
print(tensor + 10)
print(tensor * 10)
print(tensor - 10)
print(tensor / 10)


tensor([11, 12, 13])
tensor([10, 20, 30])
tensor([-9, -8, -7])
tensor([0.1000, 0.2000, 0.3000])


From the context above we can see, that the tensors are immutable within these operations.
There are also `torch` operations that do the same under the hood

In [36]:
print(torch.add(tensor, 10))
print(torch.mul(tensor, 10))
print(torch.sub(tensor, 10))
print(torch.div(tensor, 10))

tensor([11, 12, 13])
tensor([10, 20, 30])
tensor([-9, -8, -7])
tensor([0.1000, 0.2000, 0.3000])


tensor([-9, -8, -7])

tensor([0.1000, 0.2000, 0.3000])

tensor([10, 20, 30])